### ISSUE TITLE
Make test fixtures more readable

### ISSUE THREAD

**Issue by jeffcarp** [jsdom/abab#12]
Via @just-boris in https://github.com/jsdom/abab/pull/11#issuecomment-152596466

**Comment by jeffcarp** [comment]
It looks like putting the input strings in object keys won't work, because of cases like this:

```js
[
  { String.fromCharCode(0xd800, 0xdc00): null }
]
```

So I'm opting to use an array of arrays, e.g.:
```js
[
  [String.fromCharCode(0xd800, 0xdc00), null]
]
```

**Comment by just-boris** [comment]
@jeffcarp maybe some modern syntax could help you?
```
{ [String.fromCharCode(0xd800, 0xdc00)]: null }
```
This is [computed properties ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names) feature. It seems to be supported at least in iojs v3 and node.js v4.

And your solution with arrays is ok too. The main reason why I prefer object is avoiding that magical numbers

```
fixtures.forEach((fixture) => {
  const source = fixture[0];
  const expected = fixture[1];
});
```
Object with lodash would look nicer:
```
_.each(fixtures, (expected, source) => {})
```

Also we can try to play with Maps, it is supported for a long time since node 0.12

**Comment by jeffcarp** [comment]
@just-boris thanks for the suggestions!!

```
11 11 2015 16:56:57.308:INFO [IE 11.0.0 (Windows 7 0.0.0)]: Connected on socket GTtpQGbEATbcBo3iAAAB with id 63633696
IE 11.0.0 (Windows 7 0.0.0) ERROR
  Multiple definitions of a property not allowed in strict mode
  at /home/jeff/gh/jsdom/abab/test/browser.js:13815
```

**Comment by just-boris** [comment]
@jeffcarp well, our difficult test values do not allow to use it as keys. I think, that is time to get rid this idea, and keep using your array solution
```
[
  [String.fromCharCode(0xd800, 0xdc00), null]
]
```
That probably will work.

**Comment by jeffcarp** [comment]
:sob: it would have been so beautiful
