### ISSUE TITLE
"SyntaxError: Use of const in strict mode" because of commit of f22dcf1

### ISSUE THREAD

**Issue by hys928** [jsdom/abab#40]
During https://github.com/jsdom/abab/commit/f22dcf16f2488674b598ebcf56fbefcd3c58a337, it introduces the const under "use strict".

It introduces the error of "SyntaxError: Use of const in strict mode" in our app which uses the abab. 

Seems like this lib doesn't provide babel to transpile to es5.

**Comment by jeffcarp** [comment]
Thanks for the report. In which browser or environment does this fail? Can you provide repro instructions?

**Comment by hys928** [comment]
Based on the kibana log, it's happening on different browsers including chrome, safari, etc.
Unfortunately, I couldn't reproduce the issue.
But it seems like it fails the es5 compatibility check.

**Comment by hys928** [comment]
You can see the published code would fail the [es-check](https://www.npmjs.com/package/es-check)

**Comment by jeffcarp** [comment]
I'm confused, since Chrome, Safari and other major browsers have been ES6 for a long time. Do you have the specific versions of browsers that are experiencing this?

It looks like this same issue actually came up in 2015 in #15. I updated `index.js` to use `var` instead of `const` in aec14acde07c7c1c9780d709f82eaf53958dcea8, then in 2018 it was updated to `const` in f42b7b5068fa39295b340759e40a49e3f8fab5ad.

My best guess is either:
1. This error is coming from very old browsers
2. Something in your build process is not completely translating ES6 to ES5

Please let me know if you find a way to reproduce this error. Otherwise I do not think it can be investigated further.

**Comment by yjwyjw520520** [comment]
> 我很困惑，因为Chrome，Safari和其他主要浏览器已经使用ES6很长时间了。您是否遇到了特定版本的浏览器？
> 
> 看起来实际上是在2015年的[＃15中](https://github.com/jsdom/abab/issues/15)出现了同样的问题。我更新`index.js`了使用，`var`而不是`const`在[aec14ac中使用](https://github.com/jsdom/abab/commit/aec14acde07c7c1c9780d709f82eaf53958dcea8)，然后在2018年将其更新为`const`在[f42b7b5中](https://github.com/jsdom/abab/commit/f42b7b5068fa39295b340759e40a49e3f8fab5ad)。
> 
> 我最好的猜测是：
> 
> 1. 此错误来自非常老的浏览器
> 2. 您的构建过程中的某些内容并未完全将ES6转换为ES5
> 
> 如果您找到重现此错误的方法，请告诉我。否则，我认为无法对此进行进一步调查。


可以帮助我吗。我这里有一个相同的问题

Can you help me. I have the same question here

**Comment by jeffcarp** [comment]
> 可以帮助我吗。我这里有一个相同的问题
> 
> Can you help me. I have the same question here

你可以给我更多信息？你看到这个错误在哪儿？你使用什么NodeJS/browser版本？

**Comment by yjwyjw520520** [comment]
node14.9.0&nbsp; &nbsp; 运行在android5.0上面&nbsp; 出现错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jeff Carpenter"<notifications@github.com&gt;; 
发送时间: 2021年2月4日(星期四) 凌晨4:14
收件人: "jsdom/abab"<abab@noreply.github.com&gt;; 
抄送: "yjw"<1424800753@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jsdom/abab] &quot;SyntaxError: Use of const in strict mode&quot; because of commit of f22dcf1 (#40)





  
可以帮助我吗。我这里有一个相同的问题
 
Can you help me. I have the same question here
  
你可以给我更多信息？你看到这个错误在哪儿？你使用什么NodeJS/browser版本？

**Comment by jeffcarp** [comment]
Sorry for the delay @yjwyjw520520, 你可以transpile这个module或者手动地变更这个`const`？我也可以问你在什么情况你用这个module代替browser built-in atob/btoa？

**Comment by jeffcarp** [comment]
Resolving due to inactivity. Please reopen if you can repro this bug any further.

如果你可以重现这个bug，请告诉我
