### ISSUE TITLE
atob returns wrong result

### ISSUE THREAD

**Issue by otaciliolacerda** [jsdom/abab#87]
Hi, I am not familiar with this project or the spec but I've notice a different behaviour when testing in chrome/firefox and the `atob` function from this project:

Chrome/Firefox:
```
atob('/')
VM96:1 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at <anonymous>:1:1
(
```

abab:
```
atob('/') -> ""
```

**Comment by jimmywarting** [comment]
i just came here cuz i take care of `node-domexception` that solve one issue...
exposes `DOMException` that is hidden in NodeJS from v10.5 to v16.x

`DOMException` only became globally available since v17+

---

My assumption is that you do not throw a `DOMException` cuz there isn't any such error class available in NodeJS?
Correct me if i'm wrong...

But guess what. it's. With the solution i have came up with in `node-domexception` then you can get a hold of it.

what it essentially dose is transfering something impossible with postMessage and catches the constructor via a try/catch - hacky... i know.

```js
/*! node-domexception. MIT License. Jimmy Wärting <https://jimmy.warting.se/opensource> */

if (!globalThis.DOMException) {
  try {
    const { MessageChannel } = require('worker_threads'),
    port = new MessageChannel().port1,
    ab = new ArrayBuffer()
    port.postMessage(ab, [ab, ab])
  } catch (err) {
    err.constructor.name === 'DOMException' && (
      globalThis.DOMException = err.constructor
    )
  }
}

module.exports = globalThis.DOMException
```

But i have just discovered a other way to obtain it with atob.
```js
globalThis.DOMException ??= (() => { 
  try { atob(1) } catch (err) { return err.constructor } 
})()
```

undici game me this solution, and i was thinking about using it in my `node-domexception` package.

But this require using global `atob` which is only available in NodeJS v16+

I could for instance not rely on `abab` as it would simply just return `null` instead of throwing the correct `DOMException` class. 

With this said i think it's just better to rely on using NodeJS own atob/btoa implementation instead. cuz it's available in v16 globally.

And NodeJS v16 is the current LTS version out there right now. so it feels like there is little to no use for this package anymore.
So how would you feel about deprecating this package all together right now and just archive this repo? 
```
npm deprecate abab "Update to NodeJS v16+ and use global atob/btoa instead"
```
Either that or try to get hold of the global `DOMException` and throw a error instead of returning `null`

you could inline the hole `node-domexception` solution with the `worker_thread` hack i have came up with if you like...
I'm maybe likely to throw this solution out the window when i know now that there is a atob/btoa alternative solution out there now instead that don't require me to load any npm or node specific modules. as using atob would be a more cross friendlier solution

**Comment by jeffcarp** [comment]
Thanks for bringing this up. There is a comment at the [top of abab.atob](https://github.com/jsdom/abab/blob/master/lib/atob.js#L4-L5) that addresses this:

> Implementation of atob() according to the HTML and Infra specs, except that instead of throwing INVALID_CHARACTER_ERR we return null.

I'm not familiar with why that choice was made originally. It could be the lack of a native DOMException class as @jimmywarting points out.

You can catch `null` and throw your own DOMException - this is how jsdom uses abab:
https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/lib/jsdom/browser/Window.js#L759-L768

If NodeJS now has a native atob/btoa, we can look into transitioning jsdom to those and deprecating this module as long as the implementations are equivalent.
